name: Cog Unit Tests
on:
  pull_request:
  push:

jobs:
  run-tests:
    name: Run cog unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup python3
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install SFUAnime's fork of Red-DiscordBot
        run: |
          python -m pip install --upgrade pip
          pip install "Red-DiscordBot[dev] @ git+https://github.com/SFUAnime/Ren.git@V3/testing"
      - name: Run unit tests
        run: |
          pytest */test*
